name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build Docker image
    - name: Build image
      run: make build

    # Run tests inside Docker
    - name: Run tests
      run: make test-docker

    # Run linting/formatting checks
    - name: Run linters
      run: |
        docker run --rm ${{ github.event.repository.name }} ruff check .
        docker run --rm ${{ github.event.repository.name }} black --check .
        docker run --rm ${{ github.event.repository.name }} mypy src

